-- RECORDS Schema

-- !Ups
CREATE TABLE RECORDS (
  ID SERIAL PRIMARY KEY,
  NAME CHAR(50) NOT NULL,
  NUMBER CHAR(12) NOT NULL
);

INSERT INTO RECORDS (NAME, NUMBER) VALUES ('Ivanov', '+79111111111');
INSERT INTO RECORDS (NAME, NUMBER) VALUES ('Petrov', '+79222222222');
INSERT INTO RECORDS (NAME, NUMBER) VALUES ('Sidorov', '+79333333333');

-- !Downs
--drop table RECORDS;